# Generated by Django 4.1.2 on 2022-10-19 04:01

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rutinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorias_name', multiselectfield.db.fields.MultiSelectField(choices=[('gluteos', 'gluteos'), ('espalda', 'espalda'), ('abdominales', 'abdominales'), ('piernas', 'piernas'), ('brazos', 'brazos'), ('elongacion', 'elongacion')], max_length=50)),
                ('nombre', models.CharField(max_length=100)),
                ('ejercicios', models.DecimalField(decimal_places=2, max_digits=15)),
                ('alumnos', models.TextField(blank=True)),
                ('fecha', models.CharField(max_length=100)),
                ('semanalmente', models.BooleanField()),
            ],
        ),
    ]
