# Generated by Django 4.1.2 on 2022-11-01 11:54

from django.conf import settings
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo', multiselectfield.db.fields.MultiSelectField(choices=[('gluteos', 'gluteos'), ('espalda', 'espalda'), ('abdominales', 'abdominales'), ('piernas', 'piernas'), ('brazos', 'brazos'), ('elongacion', 'elongacion')], max_length=50)),
                ('nombre', models.CharField(max_length=100)),
                ('pasos', models.TextField()),
                ('icono', models.ImageField(upload_to='images/iconos/ejercicios/')),
                ('video', models.FileField(upload_to='videos/ejercicios/')),
            ],
        ),
        migrations.CreateModel(
            name='Rutinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(choices=[('hombre', 'hombre'), ('mujer', 'mujer')], default='', max_length=20)),
                ('categorias_name', multiselectfield.db.fields.MultiSelectField(choices=[('gluteos', 'gluteos'), ('espalda', 'espalda'), ('abdominales', 'abdominales'), ('piernas', 'piernas'), ('brazos', 'brazos'), ('elongacion', 'elongacion')], max_length=50)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('semanalmente', models.BooleanField()),
                ('alumnos', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('ejercicios', models.ManyToManyField(related_name='ejercicios', to='entrenamiento.ejercicio')),
            ],
        ),
    ]
