# Generated by Django 4.1.2 on 2022-11-10 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrenamiento', '0003_rutina_delete_rutinas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rutina',
            name='categorias_name',
        ),
    ]
