# Generated by Django 4.1.2 on 2022-11-10 06:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('entrenamiento', '0004_remove_rutina_categorias_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutina',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
