# Generated by Django 4.1.2 on 2022-11-10 15:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('entrenamiento', '0005_alter_rutina_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutina',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
