# Generated by Django 4.1.2 on 2022-11-10 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrenamiento', '0006_alter_rutina_fecha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ejercicio',
            old_name='video',
            new_name='archivo',
        ),
        migrations.RemoveField(
            model_name='ejercicio',
            name='icono',
        ),
    ]
