# Generated by Django 4.1.2 on 2022-11-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='foto',
            field=models.FileField(upload_to='images/news/'),
        ),
    ]
