# Generated by Django 4.1.2 on 2022-10-22 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=50)),
                ('genero', models.CharField(choices=[('hombre', 'hombre'), ('mujer', 'mujer'), ('otro', 'otro')], max_length=20)),
                ('foto_de_perfil', models.ImageField(upload_to='images/fotos_de_perfil/')),
                ('apellido', models.CharField(max_length=100)),
                ('rango', models.CharField(choices=[('alumno', 'alumno'), ('admin', 'admin'), ('profesor', 'profesor')], max_length=30)),
                ('telefono', models.CharField(max_length=15)),
                ('correo', models.CharField(max_length=100)),
                ('altura', models.CharField(max_length=5)),
                ('peso', models.CharField(max_length=5)),
                ('edad', models.CharField(max_length=3)),
                ('contraseña', models.CharField(max_length=100)),
                ('biografia', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('2_veces', '2 veces/Semana'), ('3_veces', '3 veces/Semana'), ('5_veces', '5 veces/Semana')], max_length=50)),
                ('alumno', models.ManyToManyField(to='personas.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lunes', models.IntegerField(blank=True)),
                ('martes', models.IntegerField(blank=True)),
                ('miercoles', models.IntegerField(blank=True)),
                ('jueves', models.IntegerField(blank=True)),
                ('viernes', models.IntegerField(blank=True)),
                ('turnos', models.ManyToManyField(to='personas.turno')),
            ],
        ),
    ]
