# Generated by Django 4.1.2 on 2022-10-31 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dia',
            name='turnos',
        ),
        migrations.AddField(
            model_name='turno',
            name='dias',
            field=models.ManyToManyField(to='personas.dia'),
        ),
    ]
