# Generated by Django 4.1.2 on 2022-11-10 01:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('2 veces/Semana', '2 veces/Semana'), ('3 veces/Semana', '3 veces/Semana'), ('5 veces/Semana', '5 veces/Semana')], max_length=50)),
                ('alumno', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('dias', models.ManyToManyField(to='personas.dia')),
            ],
        ),
    ]
