# Generated by Django 4.1.2 on 2022-11-03 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_remove_dia_jueves_remove_dia_lunes_remove_dia_martes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='link_playlist',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='turno',
            name='plan',
            field=models.CharField(choices=[('2 veces/Semana', '2 veces/Semana'), ('3 veces/Semana', '3 veces/Semana'), ('5 veces/Semana', '5 veces/Semana')], max_length=50),
        ),
    ]
