# Generated by Django 4.1.2 on 2022-10-31 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_alter_dia_jueves_alter_dia_lunes_alter_dia_martes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dia',
            name='jueves',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dia',
            name='lunes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dia',
            name='martes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dia',
            name='miercoles',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dia',
            name='viernes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
