# Generated by Django 4.1.2 on 2022-11-08 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_persona_link_playlist_alter_turno_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='contraseña',
            field=models.CharField(default='', max_length=100, verbose_name='Contraseña'),
        ),
    ]
