# Generated by Django 4.1.2 on 2022-11-09 06:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0004_persona_contraseña'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='alumno',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='turno',
            name='dias',
            field=models.ManyToManyField(blank=True, null=True, to='personas.dia'),
        ),
    ]
