# Generated by Django 4.1.2 on 2022-11-09 15:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0005_alter_turno_alumno_alter_turno_dias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='alumno',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='turno',
            name='dias',
            field=models.ManyToManyField(to='personas.dia'),
        ),
    ]
